name: 'Account lookup'
description: 'Account lookup...'
inputs:
  team:
    required: true
  api-url:
    required: true
  aws-region:
    required: true
    default: 'eu-west-1'
outputs:
  account:  
    description: 'Account ID'
  domain:
    description: 'Domain name'
runs:
  using: 'node16'
  main: 'dist/index.js' 