name: 'Account lookup'

permissions:
  id-token: write
  contents: read

inputs:
  team:
    required: true
  api-url:
    required: true
  aws-region:
    required: true
    default: 'eu-west-1'

outputs:
  account:
    value: ${{ steps.account.outputs.accountId }}   
runs:
  using: "composite"
  steps:
    - name: Checkout the code
      uses: actions/checkout@v3
    - name: Run script
      uses: ./account-lookup/script/
      id: script
      with:
        team: ${{ inputs.team }}
        api-url: ${{ inputs.url }}
        aws-region: ${{ inputs.aws-region }}

    - id: domain
      name: Get domain
      run: echo "The domain is ${{ steps.script.outputs.domain }}"
      shell: bash
    - id: account
      name: Get account
      run: echo "::set-output name=accountId::${{ steps.script.outputs.account }}"
      shell: bash
    - name: Echo account
      run: echo "${{ steps.account.outputs.accountId }}"
      shell: bash