name: 'Fetch account'

permissions:
  id-token: write
  contents: read

inputs:
  team:
    required: true
  api-url:
    required: true
  role-to-assume:
    required: true
  aws-region:
    required: true
    default: 'eu-west-1'
  role-session-name:
    required: true
outputs:
  account:
    value: ${{ steps.account.outputs.accountId }}   

runs:
  using: "composite"
  steps:
    - name: Checkout the code
      uses: actions/checkout@v3
        
    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Run script
      uses: ./
      id: script
      with:
        team: ${{ inputs.team }}
        api-url: ${{ inputs.url }}
        aws-region: ${{ inputs.aws-region }}

    - id: domain
      name: Get domain
      run: echo "The domain is ${{ steps.script.outputs.domain }}"
    - id: account
      name: Get account
      run: echo "::set-output name=accountId::${{ steps.script.outputs.account }}"
    - name: Echo account
      run: echo "${{ steps.account.outputs.accountId }}"